In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

c:\users\smrut\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
c:\users\smrut\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
c:\users\smrut\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


Fit SimpleImputer with one dataset and transform another dataset that SimpleImputer object

In [7]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
a = [[1, 2], [np.nan, 3], [7, 6]]
imp.fit(a) 
print(np.array(a))

[[ 1.  2.]
 [nan  3.]
 [ 7.  6.]]


In [5]:
X = [[np.nan, 2], [6, np.nan], [7, 6]]
print(np.array(X))
print(imp.transform(X)) 

[[nan  2.]
 [ 6. nan]
 [ 7.  6.]]
[[4.         2.        ]
 [6.         3.66666667]
 [7.         6.        ]]


In [6]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit_transform(X)

array([[6.5, 2. ],
       [6. , 4. ],
       [7. , 6. ]])

The SimpleImputer class also supports categorical data represented as string values or pandas categoricals when using the 'most_frequent' or 'constant' strategy:

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame([["a", "x"],[np.nan, "y"],["a", np.nan],["b", "y"]], dtype="category")
print(df)

     0    1
0    a    x
1  NaN    y
2    a  NaN
3    b    y


In [11]:
imp = SimpleImputer(strategy="most_frequent")
print(imp.fit_transform(df))   

[['a' 'x']
 ['a' 'y']
 ['a' 'y']
 ['b' 'y']]


In [13]:
import scipy.sparse as sp
X = sp.csc_matrix([[1, 2], [0, -1], [8, 4]])
print(X)

  (0, 0)	1
  (2, 0)	8
  (0, 1)	2
  (1, 1)	-1
  (2, 1)	4


In [14]:
imp = SimpleImputer(missing_values=-1, strategy='mean')
imp.fit(X)

SimpleImputer(copy=True, fill_value=None, missing_values=-1, strategy='mean',
       verbose=0)

In [17]:
imp.fit_transform(X)

<3x2 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Column format>

In [15]:
X_test = sp.csc_matrix([[-1, 2], [6, -1], [7, 6]])
print(X_test)

  (0, 0)	-1
  (1, 0)	6
  (2, 0)	7
  (0, 1)	2
  (1, 1)	-1
  (2, 1)	6


In [16]:
print(imp.transform(X_test).toarray()) 

[[3. 2.]
 [6. 3.]
 [7. 6.]]
