In [34]:
import numpy as np
import networkx

In [223]:
G = networkx.DiGraph()

In [224]:
for i in range(1,7):
    G.add_node(i)

In [225]:
V = np.array(G.nodes)
V

array([1, 2, 3, 4, 5, 6])

In [226]:
G.add_edge(1,4)
G.add_edge(4,1)
G.add_edge(1,2)
G.add_edge(2,1)
G.add_edge(1,3)
G.add_edge(3,1)
G.add_edge(2,3)
G.add_edge(3,2)
G.add_edge(3,6)
G.add_edge(6,3)
G.add_edge(3,5)
G.add_edge(5,3)
G.add_edge(5,6)
G.add_edge(6,5)

In [227]:
A = networkx.adjacency_matrix(G).A

In [228]:
D = np.diag(A.sum(axis=1))
D

array([[3, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 2]], dtype=int32)

In [229]:
T=numpy.linalg.inv(D).dot(A)
T

array([[0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ,
        0.        ],
       [0.5       , 0.        , 0.5       , 0.        , 0.        ,
        0.        ],
       [0.25      , 0.25      , 0.        , 0.        , 0.25      ,
        0.25      ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.5       , 0.        , 0.5       ,
        0.        ]])

In [230]:

for i in range(1200):
    p = np.zeros((V.shape[0],1))
    #p[np.random.uniform(0,1,V.shape[0]).argmax()]=1
    p[np.random.rand(V.shape[0]).argmax()]=1
    if i == 0:
        y = p
    else:
        y += p
y/1200

array([[0.16583333],
       [0.16916667],
       [0.17416667],
       [0.15416667],
       [0.1775    ],
       [0.15916667]])

In [244]:
walk=[]
k=20
for i in range(k):
    p = np.zeros((V.shape[0],1))
    p[np.random.rand(V.shape[0]).argmax()]=1
    p = T.dot(p)
    walk.append(p.argmax())
walk

[0, 3, 0, 1, 5, 1, 0, 4, 0, 0, 4, 3, 5, 4, 0, 5, 3, 4, 5, 1]

In [143]:
import networkx
import numpy
# let's generate a graph G
G = networkx.gnp_random_graph(5, 0.5)
# let networkx return the adjacency matrix A
A = networkx.adj_matrix(G)
A = A.todense()
A = numpy.array(A, dtype = numpy.float64)
# let's evaluate the degree matrix D
D = numpy.diag(numpy.sum(A, axis=0))
# ...and the transition matrix T
T = numpy.dot(numpy.linalg.inv(D),A)
# let's define the random walk length, say 10
walkLength = 10
# define the starting node, say the 0-th
p = numpy.array([1, 0, 0, 0, 0]).reshape(-1,1)
visited = list()
for k in range(walkLength):
    # evaluate the next state vector
    p = numpy.dot(T,p)
    # choose the node with higher probability as the visited node
    visited.append(numpy.argmax(p))

In [48]:
visited

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

In [33]:
numpy.linalg.inv(D)-1/D

C:\Users\smrut\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[  0., -inf, -inf, -inf, -inf],
       [-inf,   0., -inf, -inf, -inf],
       [-inf, -inf,   0., -inf, -inf],
       [-inf, -inf, -inf,   0., -inf],
       [-inf, -inf, -inf, -inf,   0.]])