In [1]:
import numpy as np
import networkx

In [2]:
G = networkx.DiGraph()

In [3]:
for i in range(1,7):
    G.add_node(i)

In [4]:
V = np.array(G.nodes)
V

array([1, 2, 3, 4, 5, 6])

In [5]:
G.add_edge(1,4)
G.add_edge(4,1)
G.add_edge(1,2)
G.add_edge(2,1)
G.add_edge(1,3)
G.add_edge(3,1)
G.add_edge(2,3)
G.add_edge(3,2)
G.add_edge(3,6)
G.add_edge(6,3)
G.add_edge(3,5)
G.add_edge(5,3)
G.add_edge(5,6)
G.add_edge(6,5)

In [8]:
A = networkx.adjacency_matrix(G).A
A

array([[0, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 0]], dtype=int32)

In [7]:
D = np.diag(A.sum(axis=1))
D

array([[3, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 2]], dtype=int32)

In [16]:
T=np.linalg.inv(D).dot(A)
T

array([[0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ,
        0.        ],
       [0.5       , 0.        , 0.5       , 0.        , 0.        ,
        0.        ],
       [0.25      , 0.25      , 0.        , 0.        , 0.25      ,
        0.25      ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.5       , 0.        , 0.5       ,
        0.        ]])

In [28]:
m=3
H_0 = np.ones((V.shape[0],m))
W_0 = np.random.rand(m,m)
B_0 = np.random.rand(m,m)


In [30]:
(np.linalg.inv(D).dot(A)).dot(H_0).dot(B_0) + H_0.dot(B_0)

array([[3.63216499, 1.85687058, 3.17650593],
       [3.63216499, 1.85687058, 3.17650593],
       [3.63216499, 1.85687058, 3.17650593],
       [3.63216499, 1.85687058, 3.17650593],
       [3.63216499, 1.85687058, 3.17650593],
       [3.63216499, 1.85687058, 3.17650593]])

In [31]:
(np.linalg.inv(D).dot(A))

array([[0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ,
        0.        ],
       [0.5       , 0.        , 0.5       , 0.        , 0.        ,
        0.        ],
       [0.25      , 0.25      , 0.        , 0.        , 0.25      ,
        0.25      ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.5       ],
       [0.        , 0.        , 0.5       , 0.        , 0.5       ,
        0.        ]])

In [32]:
np.linalg.inv(D)

array([[ 0.33333333,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.5       ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.25      ,  0.        ,  0.        ,
         0.        ],
       [-0.        , -0.        , -0.        ,  1.        , -0.        ,
        -0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.5       ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.5       ]])

In [33]:
A

array([[0, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 0]], dtype=int32)

In [34]:
A.dot(H_0)

array([[3., 3., 3.],
       [2., 2., 2.],
       [4., 4., 4.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [35]:
A.dot(A.dot(H_0))

array([[7., 7., 7.],
       [7., 7., 7.],
       [9., 9., 9.],
       [3., 3., 3.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [36]:
A.dot(A.dot(A.dot(H_0)))

array([[19., 19., 19.],
       [16., 16., 16.],
       [26., 26., 26.],
       [ 7.,  7.,  7.],
       [15., 15., 15.],
       [15., 15., 15.]])